import { PlaceHolderImages } from './placeholder-images';
import type { Job } from './types';

export const jobs: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    companyName: 'Innovate Inc.',
    companyLogo: PlaceHolderImages.find((img) => img.id === 'logo-innovate-inc')!,
    location: 'San Francisco, CA',
    salaryRange: '$120,000 - $160,000',
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    description: [
      'We are looking for a seasoned Senior Frontend Developer to join our dynamic team. You will be responsible for building the ‘client-side’ of our web applications.',
      'You should be able to translate our company and customer needs into functional and appealing interactive applications.',
    ],
    companyOverview:
      'Innovate Inc. is a leading tech company focused on creating cutting-edge solutions for the modern web. We value creativity, collaboration, and a passion for technology.',
    applicationDeadline: '2024-12-31',
  },
  {
    id: '2',
    title: 'Data Entry Clerk (Remote)',
    companyName: 'Global Data Solutions',
    companyLogo: PlaceHolderImages.find((img) => img.id === 'logo-global-data-solutions')!,
    location: 'Remote',
    salaryRange: '$75,000 - $85,000',
    jobType: 'Full-time',
    experienceLevel: 'Entry',
    description: [
      'Urgent hiring for a remote data entry clerk. No experience necessary!',
      'Earn a high salary from the comfort of your home. Must have a personal bank account for direct deposit of training materials fee, which will be reimbursed.',
    ],
    companyOverview: 'We are a fast-growing global company that needs motivated individuals to help us manage data.',
    applicationDeadline: '2024-11-15',
  },
  {
    id: '3',
    title: 'UX/UI Designer',
    companyName: 'Creative Co.',
    companyLogo: PlaceHolderImages.find((img) => img.id === 'logo-creative-co')!,
    location: 'New York, NY',
    salaryRange: '$90,000 - $110,000',
    jobType: 'Contract',
    experienceLevel: 'Mid',
    description: [
      'Creative Co. is seeking a talented UX/UI Designer to create amazing user experiences. The ideal candidate should have an eye for clean and artful design, possess superior UI skills and be able to translate high-level requirements into interaction flows and artifacts.',
    ],
    companyOverview:
      'We are a design agency that helps startups and established companies build beautiful and user-friendly products.',
    applicationDeadline: '2024-12-01',
  },
  {
    id: '4',
    title: 'Personal Assistant to CEO',
    companyName: 'International Holdings Group',
    companyLogo: PlaceHolderImages.find((img) => img.id === 'logo-international-holdings')!,
    location: 'Work from Home',
    salaryRange: '$95,000',
    jobType: 'Part-time',
    experienceLevel: 'Entry',
    description: [
      'Seeking a reliable personal assistant. Tasks include managing emails, scheduling, and running personal errands. Must be available via instant messenger.',
      'Contact is via a @gmail.com address. No official company website provided.',
    ],
    companyOverview: 'A high-net-worth individual is looking for personal assistance.',
    applicationDeadline: '2024-11-20',
  },
  {
    id: '5',
    title: 'Marketing Manager',
    companyName: 'GrowthHackers LLC',
    companyLogo: PlaceHolderImages.find((img) => img.id === 'logo-growthhackers')!,
    location: 'Austin, TX',
    salaryRange: '$80,000 - $100,000',
    jobType: 'Full-time',
    experienceLevel: 'Mid',
    description: [
      'We are looking for a results-driven Marketing Manager to join our team. You will be responsible for developing, implementing and executing strategic marketing plans for an entire organization in order to attract potential customers and retain existing ones.',
    ],
    companyOverview: 'GrowthHackers LLC is a startup marketing agency with a small but growing team of experts.',
    applicationDeadline: '2024-11-30',
  },
  {
    id: '6',
    title: 'Full Stack Developer',
    companyName: 'Dev Solutions',
    companyLogo: PlaceHolderImages.find((img) => img.id === 'logo-dev-solutions')!,
    location: 'Remote',
    salaryRange: '$110,000 - $140,000',
    jobType: 'Full-time',
    experienceLevel: 'Mid',
    description: [
      'Join our team as a Full Stack Developer to work on both front-end and back-end development.',
      'You will be involved in the entire product development lifecycle, from conception to deployment.',
    ],
    companyOverview: 'Dev Solutions provides comprehensive software solutions for businesses of all sizes.',
    applicationDeadline: '2025-01-15',
  },
  {
    id: '7',
    title: 'AI Developer',
    companyName: 'AI Innovators',
    companyLogo: PlaceHolderImages.find((img) => img.id === 'logo-ai-innovators')!,
    location: 'Palo Alto, CA',
    salaryRange: '$150,000 - $190,000',
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    description: [
      'We are seeking an experienced AI Developer to design and implement machine learning models.',
      'The role requires a strong background in natural language processing and computer vision.',
    ],
    companyOverview: 'AI Innovators is at the forefront of artificial intelligence research and application.',
    applicationDeadline: '2025-02-01',
  },
  {
    id: '8',
    title: 'SDE Internship',
    companyName: 'Code Crafters',
    companyLogo: PlaceHolderImages.find((img) => img.id === 'logo-code-crafters')!,
    location: 'Seattle, WA',
    salaryRange: '$30 - $40 / hour',
    jobType: 'Internship',
    experienceLevel: 'Entry',
    description: [
      'Gain hands-on experience in software development with our SDE Internship program.',
      'You will work alongside experienced engineers on real-world projects.',
    ],
    companyOverview: 'Code Crafters is a software development company that values mentorship and growth.',
    applicationDeadline: '2024-12-15',
  },
  {
    id: '9',
    title: 'Machine Learning Engineer',
    companyName: 'Quantum AI',
    companyLogo: PlaceHolderImages.find((img) => img.id === 'logo-quantum-ai')!,
    location: 'Boston, MA',
    salaryRange: '$130,000 - $170,000',
    jobType: 'Full-time',
    experienceLevel: 'Mid',
    description: [
      'As a Machine Learning Engineer, you will develop and deploy scalable machine learning solutions.',
      'A strong foundation in statistics and programming is essential for this role.',
    ],
    companyOverview: 'Quantum AI is dedicated to solving complex problems using artificial intelligence.',
    applicationDeadline: '2025-01-20',
  },
  {
    id: '10',
    title: 'Backend Developer',
    companyName: 'NextGen Tech',
    companyLogo: PlaceHolderImages.find((img) => img.id === 'logo-next-gen-tech')!,
    location: 'Remote',
    salaryRange: '$100,000 - $130,000',
    jobType: 'Full-time',
    experienceLevel: 'Mid',
    description: [
      'We are looking for a skilled Backend Developer to build and maintain the server-side of our applications.',
      'Experience with Node.js, Python, or Go is preferred.',
    ],
    companyOverview: 'NextGen Tech is a fast-growing startup creating innovative technologies for the future.',
    applicationDeadline: '2025-01-10',
  },
];
